# -*- coding:utf-8 -*-
"""
Author: liye@qiyi.com
Creation Date: 2016/11/22
Description: transfer doc(x), ppt(x), xls(x) to PDF file
"""

try:
    import sys
    import traceback
    from win32com.client import constants, gencache
except ImportError:
    print >> sys.stderr, """ !!!
    There was a problem importing one of the Python modules required.
    The error leading to this problem was:
    %s

    Please install a package which provides this module, or verify that the module is installed correctly.
    It's possible that the above module doesn't match the current version of Python, which is:
    %s

    """ % (sys.exc_info(), sys.version)
    sys.exit(1)


# transfer word file to pdf
def doc_to_pdf(input_path, output_path):
    word_generate_support()
    word = gencache.EnsureDispatch("Word.Application")
    try:
        # default value, run on background
        word.Visible = 0
        word.DisplayAlerts = 0
        doc = word.Documents.Open(input_path, ReadOnly=1)
        doc.ExportAsFixedFormat(output_path, constants.wdExportFormatPDF,
                                Item=constants.wdExportDocumentWithMarkup,
                                CreateBookmarks=constants.wdExportCreateHeadingBookmarks)
        return 0
    except Exception as e:
        traceback.format_exc()
        return 1
    finally:
        word.Quit(constants.wdDoNotSaveChanges)


# transfer ppt file to pdf
def ppt_to_pdf(input_path, output_path):
    powerpoint = gencache.EnsureDispatch('Powerpoint.application')
    try:
        powerpoint.DisplayAlerts = 0
        ppt = powerpoint.Presentations.Open(input_path)
        ppt.ExportAsFixedFormat(output_path, constants.ppFixedFormatTypePDF,
                                constants.ppFixedFormatIntentScreen, PrintRange=None)
        return 0
    except Exception as e:
        traceback.format_exc()
        return 1
    finally:
        powerpoint.Quit()


# transfer excel file to pdf
def excel_to_pdf(input_path, output_path):
    excel = gencache.EnsureDispatch('Excel.application')

    # Format setting in excel
    # ws = wb.Worksheets[1]
    # ws.PageSetup.Orientation = 2
    # ws.PageSetup.PaperSize = 9
    # ws.PageSetup.CenterHorizontally = True
    # ws.PageSetup.CenterVertically = False

    try:
        excel.DisplayAlerts = 0
        wb = excel.Workbooks.Open(input_path)
        wb.SaveAs(output_path, FileFormat=57)
        # wb.ExportAsFixedFormat(0, output)
        return 0
    except Exception as e:
        traceback.format_exc()
        return 1
    finally:
        excel.Quit()


# Generate all the support we can.
def word_generate_support():
    # enable python COM support for Word 2007
    # this is generated by: makepy.py -i "Microsoft Word 12.0 Object Library"
    gencache.EnsureModule('{00020905-0000-0000-C000-000000000046}', 0, 8, 4)
